### ISSUE TITLE
Found NAN loss

### ISSUE THREAD

**Issue by Chenglin-Yang** [sseung0703/TF2-multi-gpu-training#1]
Hi,
Thanks for this repo.
I used it but found nan loss, I used TensorFlow 2.7, cuda_11.2.

**Comment by sseung0703** [comment]
I already tested this code on TF2.5 ~ 2.8 on CUDA 10.x and 11.x,  and there is no NAN loss issue.
Could you explain your setup in detail?

**Comment by Chenglin-Yang** [comment]
I found the issue which is in my dataset loading. Thanks.
